type Contato {
  id: Int
  nome: String
  email: String
  telefone: String
}

input ContatoInput {
  nome: String
  email: String
  telefone: String
}

input FiltroInput {
  id: Int
  email: String
}

type Query {
  contatos: [Contato]
}

type Mutation {
  createContato(input: ContatoInput): Contato
  updateContato(id: Int!, input: ContatoInput): Contato
  deleteContato(input: FiltroInput): Boolean
}
